- name: Install Nginx on EC2 instances
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
